# Generated by Django 3.2.6 on 2021-12-14 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '分类',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '标签',
                'db_table': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='LeaveMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='昵称')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('createTime', models.DateField(auto_now_add=True, verbose_name='留言时间')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
                ('site', models.CharField(max_length=30, null=True, verbose_name='网址')),
                ('browserId', models.CharField(max_length=20, null=True, verbose_name='浏览器标识')),
                ('city', models.CharField(max_length=10, verbose_name='城市')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentleave', to='App_Blog.leavemsg')),
                ('replayTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='App_Blog.leavemsg')),
                ('root', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rootleave', to='App_Blog.leavemsg')),
            ],
            options={
                'verbose_name': '留言板',
                'db_table': 'LeaveMsg',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('desc', models.CharField(max_length=70, verbose_name='摘要')),
                ('body', models.TextField()),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('greatCount', models.IntegerField(default=0)),
                ('commentCount', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Blog.category', verbose_name='分类')),
                ('tags', models.ManyToManyField(blank=True, to='App_Blog.Tags', verbose_name='标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'Article',
                'ordering': ['created_time'],
            },
        ),
        migrations.CreateModel(
            name='Great',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userIp', models.GenericIPAddressField(null=True, verbose_name='IP')),
                ('isUp', models.BooleanField(default=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Blog.article')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '点赞',
                'db_table': 'Great',
                'unique_together': {('article', 'user')},
            },
        ),
    ]
