# Generated by Django 3.2.3 on 2021-06-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0002_auto_20210603_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='great',
            options={'verbose_name': '点赞'},
        ),
        migrations.AlterModelOptions(
            name='leavemsg',
            options={'verbose_name': '留言板'},
        ),
        migrations.AddField(
            model_name='leavemsg',
            name='browserId',
            field=models.CharField(default=1, max_length=20, verbose_name='浏览器标识'),
            preserve_default=False,
        ),
    ]
