# Generated by Django 3.2.3 on 2021-06-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0003_auto_20210609_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemsg',
            name='browserId',
            field=models.CharField(max_length=20, null=True, verbose_name='浏览器标识'),
        ),
    ]
