# Generated by Django 3.2.3 on 2021-06-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0004_alter_leavemsg_browserid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavemsg',
            old_name='replay',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='leavemsg',
            name='site',
            field=models.CharField(max_length=30, null=True, verbose_name='网址'),
        ),
    ]
