# Generated by Django 3.2.3 on 2021-06-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0005_auto_20210611_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemsg',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='邮箱'),
        ),
    ]
