# Generated by Django 3.2.3 on 2021-06-11 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0006_leavemsg_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavemsg',
            name='parent',
        ),
    ]
