# Generated by Django 3.2.3 on 2021-06-11 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0007_remove_leavemsg_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemsg',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App_Blog.leavemsg'),
        ),
    ]
