# Generated by Django 3.2.3 on 2021-06-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0008_leavemsg_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemsg',
            name='city',
            field=models.CharField(default=1, max_length=10, verbose_name='城市'),
            preserve_default=False,
        ),
    ]
