# Generated by Django 3.2.3 on 2021-06-12 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0010_auto_20210612_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavemsg',
            old_name='replay',
            new_name='replayTo',
        ),
    ]
