# Generated by Django 3.2.6 on 2021-12-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthrelationship',
            name='avata',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='oauthrelationship',
            name='nickname',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
