# Generated by Django 3.2.3 on 2021-06-03 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Blog', '0002_auto_20210603_1618'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now_add=True)),
                ('body', models.TextField()),
                ('browserId', models.CharField(max_length=24)),
                ('articleId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='App_Blog.article')),
                ('parentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parentComment', to='APP_Comment.comment')),
                ('replayTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replies', to=settings.AUTH_USER_MODEL)),
                ('root', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rootComment', to='APP_Comment.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment',
                'ordering': ['-time'],
            },
        ),
    ]
