# Generated by Django 3.2.3 on 2021-06-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-time'], 'verbose_name': '评论'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='browserId',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
