# Generated by Django 3.2.3 on 2021-06-04 02:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('date', models.DateField(auto_now_add=True)),
                ('body', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': '随笔',
                'db_table': 'essay',
            },
        ),
    ]
